version: "3"
services:
  nginx:
    image: nginx:customized
    build: ./nginx
    container_name: rev
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf/ssl:/etc/nginx/ssl:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    restart: always
