version: '3'
services:
  mysql:
    image: mariadb:customized
    build: ./requirements/mariadb
    volumes:
      - ${MOUNT_DIR}/mysql:/var/lib/mysql
      - ./requirements/mariadb/tools:/tools
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASS}
    restart: always
  wordpress:
    image: wordpress:customized
    build: ./requirements/wordpress
    volumes:
      - ${MOUNT_DIR}/html:/var/www/html # same location with nginx vol
      - ./requirements/mariadb/conf:/conf
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${USER_NAME}
      WORDPRESS_DB_PASSWORD: ${USER_PASS}
      WORDPRESS_ADMIN: ${WP_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD: ${WP_ADMIN_PASS}
      WORDPRESS_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WORDPRESS_USER: ${WP_USER_NAME}
      WORDPRESS_USER_PASSWORD: ${WP_USER_PASS}
      WORDPRESS_USER_EMAIL: ${WP_USER_EMAIL}
    restart: always
  nginx:
    image: nginx:customized
    build: ./requirements/nginx
    container_name: rev
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ${MOUNT_DIR}/html:/var/www/html # same location with wordpress vol
    depends_on:
      - wordpress
    restart: always
networks:
  default:
    driver: bridge