version: '3'
services:
  mariadb:
    image: mariadb:customized
    build: ./requirements/mariadb
    volumes:
      - /data20/mysql:/var/lib/mysql # (TO DO: change mount point)
      - ./requirements/mariadb/tools:/tools
    env_file:
      - ./.env
    restart: always
  wordpress:
    image: wordpress:customized
    build: ./requirements/wordpress
    volumes:
      - /data20/html:/var/www/html # same location with nginx vol
      - ./requirements/mariadb/conf:/conf
    depends_on:
      - mariadb
    env_file:
      - ./.env
    restart: always
  nginx:
    image: nginx:customized
    build: ./requirements/nginx
    container_name: rev
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - /data20/html:/var/www/html # same location with wordpress vol
    depends_on:
      - wordpress
    env_file:
      - ./.env
    restart: always
networks:
  default:
    driver: bridge