version: '3'
services:
  mysql:
    #image: mariadb # 11.0.2 (latest)
    image: mariadb:customized
    build: ./requirements/mariadb
    volumes:
      - /data5/mysql:/var/lib/mysql
      - ./requirements/mariadb/tools:/tools
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASS}
    restart: always
  wordpress:
    #image: wordpress:php8.0-fpm-alpine #ok
    image: wordpress:racoon
    build: ./requirements/wordpress
    volumes:
      - /data5/html:/var/www/html # same location with nginx vol
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${USER_NAME}
      WORDPRESS_DB_PASSWORD: ${USER_PASS}
      WORDPRESS_TABLE_PREFIX: wp_
    restart: always
  nginx:
    image: nginx:customized
    build: ./requirements/nginx
    container_name: rev
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - /data5/html:/var/www/html # same location with wordpress vol
    depends_on:
      - wordpress
    restart: always
networks:
  default:
    driver: bridge